"""Offline, metadata-only parser infrastructure used by the fiscal watcher."""

from agent.parsers.contracts import (
    DocumentContext,
    DocumentParser,
    DocumentSignal,
    ExtractionStatus,
    ParserExtraction,
    ParserRunResult,
    SignalProvenance,
    TechnicalFormat,
)
from agent.parsers.das_pdf import DasComponent, DasDocument, DasHeader, DasPdfParser, DasValidation
from agent.parsers.darf_pdf import DarfDocument, DarfFile, DarfHeader, DarfPdfParser, DarfRevenue, DarfValidation
from agent.parsers.layout_framework import (
    ClassificationResult,
    ComposableDocumentParser,
    DocumentClassifier,
    DocumentLayoutDetector,
    DocumentLayoutExtractor,
    LayoutIdentification,
    LayoutRegistry,
    SanitizedLayoutDiagnostic,
    default_layout_registry,
    sanitized_layout_diagnostic,
)
from agent.parsers.mit_json import (
    MitAssessmentPeriod,
    MitDebit,
    MitDebitListKind,
    MitDocument,
    MitInitialData,
    MitJsonParser,
    MitSpecialEvent,
    MitSuspension,
    MitValidation,
    sanitized_mit_json_probe,
)
from agent.parsers.mit_revenue_codes import (
    MIT_REVENUE_CATALOG_VERSION,
    MIT_REVENUE_CODES,
    MitRevenueCode,
    lookup_mit_revenue_code,
)
from agent.parsers.runtime import DocumentParserRuntime, ParserRegistry, default_parser_registry
from agent.parsers.state_guide_pdf import StateGuideDocument, StateGuideFile, StateGuidePdfParser
from agent.parsers.state_revenue_guide import StateComponent, StateGuideHeader, StateGuideValidation, StateRevenue, StateRevenueGuideExtractor

__all__ = [
    "DocumentContext",
    "DocumentClassifier",
    "DocumentLayoutDetector",
    "DocumentLayoutExtractor",
    "DocumentParser",
    "DocumentParserRuntime",
    "DocumentSignal",
    "DasComponent",
    "DasDocument",
    "DasHeader",
    "DasPdfParser",
    "DasValidation",
    "DarfDocument",
    "DarfFile",
    "DarfHeader",
    "DarfPdfParser",
    "DarfRevenue",
    "DarfValidation",
    "ClassificationResult",
    "ComposableDocumentParser",
    "ExtractionStatus",
    "ParserExtraction",
    "ParserRegistry",
    "ParserRunResult",
    "LayoutIdentification",
    "LayoutRegistry",
    "MitAssessmentPeriod",
    "MitDebit",
    "MitDebitListKind",
    "MitDocument",
    "MitInitialData",
    "MitJsonParser",
    "MitRevenueCode",
    "MitSpecialEvent",
    "MitSuspension",
    "MitValidation",
    "MIT_REVENUE_CATALOG_VERSION",
    "MIT_REVENUE_CODES",
    "SanitizedLayoutDiagnostic",
    "SignalProvenance",
    "TechnicalFormat",
    "StateComponent",
    "StateGuideDocument",
    "StateGuideFile",
    "StateGuideHeader",
    "StateGuidePdfParser",
    "StateGuideValidation",
    "StateRevenue",
    "StateRevenueGuideExtractor",
    "default_parser_registry",
    "default_layout_registry",
    "sanitized_layout_diagnostic",
    "sanitized_mit_json_probe",
    "lookup_mit_revenue_code",
]
