from __future__ import annotations

from enum import Enum


class ReconciliationStatus(str, Enum):
    CONFIRMADO_ARQUIVO_ACESSORIAS = "CONFIRMADO_ARQUIVO_ACESSORIAS"
    CONFIRMADO_API = "CONFIRMADO_API"
    CONFIRMADO_ARQUIVO = "CONFIRMADO_ARQUIVO"
    PENDENTE = "PENDENTE"
    PENDENTE_SEM_ARQUIVO = "PENDENTE_SEM_ARQUIVO"
    DIVERGENTE = "DIVERGENTE"
    DISPENSADO_AUTOMATICAMENTE = "DISPENSADO_AUTOMATICAMENTE"
    NAO_APLICAVEL = "NAO_APLICAVEL"
    BAIXA_CONFIANCA = "BAIXA_CONFIANCA"
    CONFERENCIA_MANUAL = "CONFERENCIA_MANUAL"


class Department(str, Enum):
    FISCAL = "FISCAL"
    DP = "DP"
    COMPARTILHADO = "COMPARTILHADO"
    SISTEMA = "SISTEMA"


class ActivityType(str, Enum):
    COMERCIO = "COMERCIO"
    INDUSTRIA = "INDUSTRIA"
    SERVICOS = "SERVICOS"
    SERVICOS_MEDICOS_ODONTOLOGICOS = "SERVICOS_MEDICOS_ODONTOLOGICOS"
    SERVICOS_IMOBILIARIOS = "SERVICOS_IMOBILIARIOS"
    TEMPLO_RELIGIOSO = "TEMPLO_RELIGIOSO"


class FiscalRegime(str, Enum):
    SIMPLES_NACIONAL = "SIMPLES_NACIONAL"
    MEI = "MEI"
    LUCRO_PRESUMIDO = "LUCRO_PRESUMIDO"
    LUCRO_REAL = "LUCRO_REAL"
    IMUNE_ISENTA = "IMUNE_ISENTA"


class EconetSemanticStatus(str, Enum):
    ALLOWED = "ALLOWED"
    PROHIBITED = "PROHIBITED"
    NOT_ALLOWED = "NOT_ALLOWED"
    NOT_MANDATORY = "NOT_MANDATORY"
    MANDATORY = "MANDATORY"
    PARSED = "PARSED"
    NOT_OBSERVED = "NOT_OBSERVED"
    UNKNOWN = "UNKNOWN"
    PARSE_ERROR = "PARSE_ERROR"
    REGIME_PROHIBITED = "REGIME_PROHIBITED"
    REGIME_NOT_ALLOWED = "REGIME_NOT_ALLOWED"
    EMPTY = "EMPTY"


class EconetCacheWriteStatus(str, Enum):
    CREATED = "CREATED"
    UPDATED = "UPDATED"
    UNCHANGED = "UNCHANGED"
    WOULD_CREATE = "WOULD_CREATE"
    WOULD_UPDATE = "WOULD_UPDATE"
    WOULD_REMAIN_UNCHANGED = "WOULD_REMAIN_UNCHANGED"


FISCAL_REGIME_LABELS: dict[FiscalRegime, str] = {
    FiscalRegime.SIMPLES_NACIONAL: "Simples Nacional",
    FiscalRegime.MEI: "MEI",
    FiscalRegime.LUCRO_PRESUMIDO: "Lucro Presumido",
    FiscalRegime.LUCRO_REAL: "Lucro Real",
    FiscalRegime.IMUNE_ISENTA: "Imune/Isenta",
}
